# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-03 19:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('werewolf', '0002_auto_20170901_1629'),
    ]

    operations = [
        migrations.CreateModel(
            name='Remark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_no', models.IntegerField()),
                ('days', models.IntegerField(default=1)),
                ('types', models.IntegerField(default=1)),
                ('user', models.CharField(max_length=200, verbose_name='発言者')),
                ('text', models.TextField(verbose_name='発言')),
            ],
        ),
        migrations.CreateModel(
            name='Village',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='村名')),
                ('auther', models.CharField(max_length=200, verbose_name='作成者')),
                ('character', models.CharField(max_length=200, verbose_name='キャラセット')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='remark',
            name='village',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='werewolf.Village'),
        ),
    ]
