# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-03 19:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('werewolf', '0003_auto_20170903_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remark',
            name='user',
            field=models.CharField(default='unknown', max_length=200, verbose_name='発言者'),
        ),
    ]
