# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-04 00:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('werewolf', '0006_remark_character'),
    ]

    operations = [
        migrations.AlterField(
            model_name='village',
            name='auther',
            field=models.CharField(max_length=200, verbose_name='村主'),
        ),
    ]
