# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-04 00:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('werewolf', '0007_auto_20170904_0010'),
    ]

    operations = [
        migrations.AddField(
            model_name='remark',
            name='character_img_url',
            field=models.CharField(default='rain/01.png', max_length=100),
        ),
    ]
