# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-13 01:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('werewolf', '0010_auto_20170913_0112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remark',
            name='text',
            field=models.TextField(verbose_name='発言'),
        ),
    ]
