# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-16 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('werewolf', '0011_auto_20170913_0136'),
    ]

    operations = [
        migrations.AddField(
            model_name='village',
            name='delflag',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='village',
            name='endflag',
            field=models.IntegerField(default=0),
        ),
    ]
