# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-16 20:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('werewolf', '0012_auto_20170916_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='remark',
            name='user_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
