# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-17 19:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('werewolf', '0014_resident_delflag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resident',
            name='delflag',
        ),
    ]
