# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-17 20:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('werewolf', '0016_remark_delflag'),
    ]

    operations = [
        migrations.AddField(
            model_name='village',
            name='palflag',
            field=models.IntegerField(default=0),
        ),
    ]
