# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-18 00:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('werewolf', '0017_village_palflag'),
    ]

    operations = [
        migrations.AddField(
            model_name='remark',
            name='charaset',
            field=models.CharField(default='rain', max_length=30, verbose_name='キャラセット'),
        ),
        migrations.AddField(
            model_name='resident',
            name='charaset',
            field=models.CharField(default='rain', max_length=30, verbose_name='キャラセット'),
        ),
    ]
