# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-17 08:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('werewolf', '0018_auto_20170917_0810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remark',
            name='user_id',
            field=models.ForeignKey(default=21, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
