# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-18 02:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('werewolf', '0019_village_character_img_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='village',
            name='character_name',
            field=models.CharField(default='霧雨降る街', max_length=200),
        ),
        migrations.AlterField(
            model_name='village',
            name='character',
            field=models.CharField(default='rain', max_length=200, verbose_name='キャラセット'),
        ),
    ]
