# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-18 19:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('werewolf', '0020_auto_20170918_0245'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='winflag',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='village',
            name='days',
            field=models.IntegerField(default=0, verbose_name='何日目'),
        ),
        migrations.AddField(
            model_name='village',
            name='nightflag',
            field=models.IntegerField(default=0),
        ),
    ]
