# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-18 19:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('werewolf', '0021_auto_20170918_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='village',
            name='started_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
