# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-18 20:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('werewolf', '0023_remark_nightflag'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='job',
            field=models.CharField(default='村人', max_length=100, verbose_name='役職'),
        ),
        migrations.AlterField(
            model_name='remark',
            name='days',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='resident',
            name='position',
            field=models.CharField(default='無効', max_length=100, verbose_name='不使用カラム'),
        ),
    ]
