# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-18 20:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('werewolf', '0026_auto_20170918_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='village',
            name='startflag',
            field=models.IntegerField(default=0),
        ),
    ]
