# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-18 21:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('werewolf', '0027_village_startflag'),
    ]

    operations = [
        migrations.AddField(
            model_name='village',
            name='daytime_length',
            field=models.IntegerField(default=600),
        ),
        migrations.AddField(
            model_name='village',
            name='nighttime_length',
            field=models.IntegerField(default=180),
        ),
        migrations.AddField(
            model_name='village',
            name='updated_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
