# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-21 23:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('werewolf', '0032_auto_20170920_0108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='village',
            name='auther',
            field=models.CharField(default='system', max_length=200, verbose_name='村主'),
        ),
    ]
