# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-21 23:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('werewolf', '0033_auto_20170921_2353'),
    ]

    operations = [
        migrations.RenameField(
            model_name='village',
            old_name='auther',
            new_name='auther_name',
        ),
    ]
