# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-22 00:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('werewolf', '0035_village_auther'),
    ]

    operations = [
        migrations.RenameField(
            model_name='village',
            old_name='character',
            new_name='charaset',
        ),
        migrations.RenameField(
            model_name='village',
            old_name='character_name',
            new_name='charaset_name',
        ),
    ]
