# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-22 00:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('werewolf', '0036_auto_20170922_0011'),
    ]

    operations = [
        migrations.RenameField(
            model_name='village',
            old_name='daytime_length',
            new_name='daytime_seconds',
        ),
        migrations.RenameField(
            model_name='village',
            old_name='nighttime_length',
            new_name='nighttime_seconds',
        ),
    ]
