# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-22 00:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('werewolf', '0038_auto_20170922_0027'),
    ]

    operations = [
        migrations.RenameField(
            model_name='remark',
            old_name='days',
            new_name='day',
        ),
        migrations.RenameField(
            model_name='village',
            old_name='days',
            new_name='day',
        ),
    ]
