# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-22 00:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('werewolf', '0039_auto_20170922_0034'),
    ]

    operations = [
        migrations.RenameField(
            model_name='remark',
            old_name='user_id',
            new_name='remarker',
        ),
    ]
