# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-23 19:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('werewolf', '0042_auto_20170922_0106'),
    ]

    operations = [
        migrations.CreateModel(
            name='Execute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('execute_type', models.CharField(default='none', max_length=30)),
                ('executer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executer', to='werewolf.Resident')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target', to='werewolf.Resident')),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='werewolf.Village')),
            ],
        ),
        migrations.RenameField(
            model_name='remark',
            old_name='types',
            new_name='remark_type',
        ),
    ]
