# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-23 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('werewolf', '0043_auto_20170923_1922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resident',
            name='types',
        ),
        migrations.AlterField(
            model_name='remark',
            name='remark_type',
            field=models.CharField(default='none', max_length=30),
        ),
    ]
