# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-24 02:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('werewolf', '0044_auto_20170923_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='execute',
            name='day',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='remark',
            name='icon_url',
            field=models.CharField(default='A.png', max_length=100),
        ),
        migrations.AlterField(
            model_name='resident',
            name='icon_url',
            field=models.CharField(default='A.png', max_length=100),
        ),
        migrations.AlterField(
            model_name='village',
            name='icon_url',
            field=models.CharField(default='A.png', max_length=200),
        ),
    ]
