# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-24 22:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('werewolf', '0045_auto_20170924_0212'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
